spring.application.name=ivents-ui-support

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ivents_pt
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.username=
#spring.data.redis.password=
spring.cache.type=redis
